apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate-deployment
  labels:
    app: aggregate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregate
  template:
    metadata:
      labels:
        app: aggregate
    spec:
      containers:
      - name: aggregate
        image: sanbagh/userorderaggregator:latest
        ports:
        - containerPort: 80
        env:
        - name: Values__userUrl
          valueFrom: 
            configMapKeyRef:
              name: sqlserver-configmap
              key: user_service
        - name: Values__ordersUrl
          valueFrom:
            configMapKeyRef:
              name: sqlserver-configmap
              key: order_service
        - name: Values__userport
          valueFrom:
            configMapKeyRef:
              name: sqlserver-configmap
              key: user_port
        - name: Values__jaeger-host
          valueFrom: 
            configMapKeyRef:
              name: sqlserver-configmap
              key: jaeger_host
        - name: Values__orderport
          valueFrom:
            configMapKeyRef:
              name: sqlserver-configmap
              key: order_port
---
apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
spec:
  selector:
    app: aggregate
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
