apiVersion: apps/v1 
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment-pod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: order-deployment-pod
    spec:
      containers:
      - name: order
        image: nginx:1.14.2
        ports:
        - containerPort: 80