apiVersion: v1
kind: Service
metadata:
  name: sql-server
  labels:
    app: sqlserver
spec:
  ports:
    - port: 1433
  selector:
    app: sqlserver
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pv-claim
  labels:
    app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sql-server
  labels:
    app: sqlserver
spec:
  selector:
    matchLabels:
      app: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server
        name: sqlserver
        env:
        - name: ACCEPT_EULA
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: accept_eula
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: sql-password
        ports:
        - containerPort: 1433
          name: sqlserver
        volumeMounts:
        - name: sqlserver-persistent-storage
          mountPath: /var/lib/sqlserver
      volumes:
      - name: sqlserver-persistent-storage
        persistentVolumeClaim:
          claimName: sqlserver-pv-claim
